### ISSUE TITLE
npm module name

### ISSUE THREAD

**Issue by brrd** [alanshaw/br-chrome-tabs#4]
@adamschwartz and I would like to publish [the original chrome-tabs module](https://github.com/adamschwartz/chrome-tabs) on npm under the name `chrome-tabs`, but we noticed you are already using this name for br-chrome-tabs. 

@alanshaw would you agree to rename your npm module to let @adamschwartz take over this name? We believe this would be clearer for users.

If you accept, I could contact the npm team to ask for the change. Otherwise we would publish chrome-tabs under another name.

Our full discussion: https://github.com/adamschwartz/chrome-tabs/pull/31#issuecomment-329553966

Thank you!

**Comment by alanshaw** [comment]
Yes I'd be happy to rename

**Comment by brrd** [comment]
Great, thank you!
I'll write an email to NPM.
@adamschwartz please send me your email address (contact at brrd dot fr) if you want to be in CC.

**Comment by brrd** [comment]
This is done, we'll publish it soon.
Thank you very much again @alanshaw
